"""Initial clean migration

Revision ID: 319da3df4c49
Revises: 
Create Date: 2025-02-12 22:41:35.564735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319da3df4c49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applied_jobs', sa.Column('application_id', sa.Integer(), nullable=False))
    op.add_column('applied_jobs', sa.Column('applied_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('applied_jobs', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applied_jobs', 'seeker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_applied_jobs_id', table_name='applied_jobs')
    op.create_index(op.f('ix_applied_jobs_application_id'), 'applied_jobs', ['application_id'], unique=False)
    op.drop_constraint('applied_jobs_seeker_id_fkey', 'applied_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'applied_jobs', 'job_seekers', ['seeker_id'], ['seeker_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applied_jobs', 'jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_column('applied_jobs', 'id')
    op.add_column('job_seekers', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('job_seekers', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'job_seekers', ['user_id'])
    op.drop_constraint('job_seekers_user_id_fkey', 'job_seekers', type_='foreignkey')
    op.create_foreign_key(None, 'job_seekers', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('recruitment_agencies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('recruitment_agencies', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'recruitment_agencies', ['user_id'])
    op.create_foreign_key(None, 'recruitment_agencies', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'recruitment_agencies', type_='foreignkey')
    op.drop_constraint(None, 'recruitment_agencies', type_='unique')
    op.drop_column('recruitment_agencies', 'created_at')
    op.drop_column('recruitment_agencies', 'user_id')
    op.drop_constraint(None, 'job_seekers', type_='foreignkey')
    op.create_foreign_key('job_seekers_user_id_fkey', 'job_seekers', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'job_seekers', type_='unique')
    op.alter_column('job_seekers', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('job_seekers', 'created_at')
    op.add_column('applied_jobs', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'applied_jobs', type_='foreignkey')
    op.drop_constraint(None, 'applied_jobs', type_='foreignkey')
    op.create_foreign_key('applied_jobs_seeker_id_fkey', 'applied_jobs', 'job_seekers', ['seeker_id'], ['seeker_id'])
    op.drop_index(op.f('ix_applied_jobs_application_id'), table_name='applied_jobs')
    op.create_index('ix_applied_jobs_id', 'applied_jobs', ['id'], unique=False)
    op.alter_column('applied_jobs', 'seeker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applied_jobs', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('applied_jobs', 'applied_at')
    op.drop_column('applied_jobs', 'application_id')
    # ### end Alembic commands ###
